name: "Local Cache"
description: "Like actions/cache, but using a runner-local directory"
inputs:
  path:
    description: "A list of files, directories, and wildcard patterns to cache and restore"
    required: true
  key:
    description: "An explicit key for restoring and saving the cache"
    required: true
  restore-keys:
    description: "An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case."
    required: false
  cache-dir:
    description: "Absolute path in the runner where the cache files are stored"
    required: true
outputs:
  cache-hit:
    description: "A boolean value to indicate an exact match was found for the primary key"
runs:
  using: "node16"
  main: "dist/restore/index.js"
  post: "dist/save/index.js"
  post-if: success()
